import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowRight, Camera, Check, ChevronDown, CircleUserRound, CreditCard, Leaf, MapPin, Menu, Package, Phone, Plus, ShoppingBag, ShieldCheck, Truck, X } from 'lucide-react'

type Product = { id: number; name: string; price: number; weight: string; image: string; category: string; description: string }
type CartLine = Product & { quantity: number }
type Order = { id: string; date: string; customer: string; total: number; status: string; payment: string; items: number }

const starterProducts: Product[] = [
  { id: 1, name: 'Salsiccia dolce di maiale', price: 7.5, weight: '500 g', category: 'Insaccati', description: 'Ricetta di famiglia, dal gusto pieno e delicato.', image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=900&q=85' },
  { id: 2, name: 'Soppressata di maiale', price: 8.5, weight: '400 g', category: 'Salumi', description: 'Lenta stagionatura e tagli italiani selezionati.', image: 'https://images.unsplash.com/photo-1524438418049-ab2acb78927d?auto=format&fit=crop&w=900&q=85' },
  { id: 3, name: 'Trancio di pancetta tesa', price: 3.5, weight: '250 g', category: 'Salumi', description: 'Morbida, saporita, fatta secondo tradizione.', image: 'https://images.unsplash.com/photo-1619012655280-484e4ba1c3c2?auto=format&fit=crop&w=900&q=85' },
  { id: 4, name: 'Capicollo di maiale', price: 14.5, weight: '500 g', category: 'Salumi', description: 'Un grande classico valdianese da condividere.', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=85' },
  { id: 5, name: 'Guanciale al trancio', price: 3.5, weight: '250 g', category: 'Salumi', description: 'Perfetto per ricette dal sapore inconfondibile.', image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=85' },
  { id: 6, name: 'Box degustazione', price: 30, weight: '1,2 kg', category: 'Box regalo', description: 'Una selezione dei nostri sapori più autentici.', image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=85' },
]

const money = (n:number) => new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n)

export default function App() {
  const [products, setProducts] = useState<Product[]>(() => JSON.parse(localStorage.getItem('doc-products') || 'null') || starterProducts)
  const [cart, setCart] = useState<CartLine[]>(() => JSON.parse(localStorage.getItem('doc-cart') || '[]'))
  const [orders, setOrders] = useState<Order[]>(() => JSON.parse(localStorage.getItem('doc-orders') || '[]'))
  const [drawer, setDrawer] = useState(false), [menu, setMenu] = useState(false), [checkout, setCheckout] = useState(false), [admin, setAdmin] = useState(false), [notice, setNotice] = useState('')
  useEffect(()=>localStorage.setItem('doc-products',JSON.stringify(products)),[products])
  useEffect(()=>localStorage.setItem('doc-cart',JSON.stringify(cart)),[cart])
  useEffect(()=>localStorage.setItem('doc-orders',JSON.stringify(orders)),[orders])
  const total = useMemo(()=>cart.reduce((x,p)=>x+p.price*p.quantity,0),[cart])
  const add = (p:Product) => { setCart(c=>{const found=c.find(x=>x.id===p.id); return found?c.map(x=>x.id===p.id?{...x,quantity:x.quantity+1}:x):[...c,{...p,quantity:1}]}); setNotice(`${p.name} aggiunto al carrello`); setTimeout(()=>setNotice(''),2500) }
  const update = (id:number, delta:number) => setCart(c=>c.flatMap(x=>x.id===id && x.quantity+delta<1?[]:x.id===id?[{...x,quantity:x.quantity+delta}]:[x]))
  const submitOrder = (e:FormEvent<HTMLFormElement>) => { e.preventDefault(); const data=new FormData(e.currentTarget); const customer=String(data.get('name')); setOrders(o=>[{id:`DOC-${String(1042+o.length)}`,date:new Date().toLocaleDateString('it-IT'),customer,total,status:'Da confermare',payment:String(data.get('payment')),items:cart.reduce((x,p)=>x+p.quantity,0)},...o]); setCart([]);setCheckout(false);setDrawer(false);setNotice('Ordine ricevuto! Ti contatteremo per la conferma.') }
  const createProduct=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);setProducts(p=>[...p,{id:Date.now(),name:String(d.get('name')),price:Number(d.get('price')),weight:String(d.get('weight')),category:'Novità',description:String(d.get('description')),image:String(d.get('image'))||starterProducts[0].image}]);e.currentTarget.reset();setNotice('Prodotto pubblicato nel catalogo.')}
  return <main>
    <div className="topbar">Spedizione gratuita da 60€ <span>•</span> Consegna in 48 ore <span>•</span> Pagamenti sicuri</div>
    <header><a className="brand" href="#inizio"><i>DOC</i><b>CARNI</b><small>DAL 1961 · ATENA LUCANA</small></a><nav className={menu?'open':''}><a href="#storia">La nostra storia</a><a href="#shop">Lo shop</a><a href="#qualita">La qualità</a><a href="#contatti">Contatti</a></nav><div className="head-actions"><button onClick={()=>setAdmin(true)} aria-label="Area riservata"><CircleUserRound/></button><button className="cart-button" onClick={()=>setDrawer(true)} aria-label="Carrello"><ShoppingBag/><em>{cart.reduce((x,p)=>x+p.quantity,0)}</em></button><button className="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
    {notice && <div className="toast"><Check/> {notice}</div>}
    <section className="hero" id="inizio"><div className="hero-copy"><p className="eyebrow">L’INNOVAZIONE DEL GUSTO DELLE TRADIZIONI</p><h1>Il sapore vero<br/><i>del Vallo di Diano.</i></h1><p>Salumi artigianali, carni italiane certificate e quarant’anni di famiglia in ogni fetta.</p><a className="button cream" href="#shop">Scopri i prodotti <ArrowRight/></a></div><div className="hero-photo"><div className="stamp">40<br/><small>ANNI DI<br/>TRADIZIONE</small></div></div></section>
    <section className="promises" id="qualita"><div><Leaf/><b>Solo carni italiane</b><span>Tagli selezionati e certificati</span></div><div><ShieldCheck/><b>Autenticamente genuini</b><span>Senza glutine, lattosio e conservanti</span></div><div><Truck/><b>A casa tua in 48 ore</b><span>Spedizione gratuita oltre 60€</span></div></section>
    <section className="story" id="storia"><div className="story-image"></div><div className="story-copy"><p className="eyebrow">UNA STORIA LUNGA 40 ANNI</p><h2>La tradizione<br/><i>ha un sapore.</i></h2><p>DOC Carni nasce dalla passione e dalla determinazione di Gerardo e Angela. Un percorso ispirato alle ricette contadine e al rispetto per una materia prima d’eccellenza.</p><p>Oggi la famiglia continua a custodire ogni gesto: la scelta della carne, la lavorazione, il tempo necessario perché un prodotto sia davvero buono.</p><a href="#shop" className="text-link">Conosci DOC Carni <ArrowRight/></a></div></section>
    <section className="shop" id="shop"><div className="section-heading"><div><p className="eyebrow">DALLA NOSTRA BOTTEGA A CASA TUA</p><h2>I preferiti <i>di DOC.</i></h2></div><button className="filter">Tutti i prodotti <ChevronDown/></button></div><div className="products">{products.map(p=><article className="product" key={p.id}><div className="product-image" style={{backgroundImage:`url(${p.image})`}}><span>{p.category}</span><button onClick={()=>add(p)} aria-label={`Aggiungi ${p.name}`}><Plus/></button></div><div className="product-info"><small>{p.weight}</small><h3>{p.name}</h3><p>{p.description}</p><b>{money(p.price)}</b></div></article>)}</div></section>
    <section className="manifesto"><div><p className="eyebrow">LA NOSTRA PROMESSA</p><h2>Gusto autentico.<br/><i>Cura assoluta.</i></h2></div><p>Ogni prodotto DOC Carni racconta un territorio e un modo di fare le cose: con pazienza, con rispetto, senza scorciatoie.</p></section>
    <footer id="contatti"><div className="footer-brand"><a className="brand"><i>DOC</i><b>CARNI</b><small>DAL 1961 · ATENA LUCANA</small></a><p>Il vero sapore della tradizione valdianese.</p></div><div><h4>Visita la bottega</h4><p><MapPin/> Via Quercia, 6<br/>84030 Atena Lucana (SA)</p></div><div><h4>Parliamone</h4><p><Phone/> +39 335 5280842<br/>+39 0975 711 09</p><p>doccarni1961@gmail.com</p></div><div><h4>Seguici</h4><a href="https://www.instagram.com/doccarniofficial/" target="_blank"><Camera/> Instagram</a><a href="https://www.facebook.com/doccarni" target="_blank">Facebook</a></div><small className="copyright">© 2026 DOC Carni · P.IVA e condizioni di vendita da inserire prima della pubblicazione.</small></footer>
    {drawer && <aside className="overlay"><div className="cart"><button className="close" onClick={()=>setDrawer(false)}><X/></button><p className="eyebrow">IL TUO CARRELLO</p><h2>Buone scelte.</h2>{cart.length===0?<div className="empty"><ShoppingBag/><p>Il tuo carrello è ancora vuoto.</p><a onClick={()=>setDrawer(false)} href="#shop">Vai allo shop</a></div>:<><div className="cart-lines">{cart.map(x=><div key={x.id}><img src={x.image}/><span><b>{x.name}</b><small>{money(x.price)}</small><label><button onClick={()=>update(x.id,-1)}>−</button>{x.quantity}<button onClick={()=>update(x.id,1)}>+</button></label></span><strong>{money(x.price*x.quantity)}</strong></div>)}</div><div className="cart-total"><span>Subtotale</span><b>{money(total)}</b><small>{total>=60?'Spedizione gratuita inclusa':'Spedizione calcolata al checkout'}</small></div><button className="button dark full" onClick={()=>setCheckout(true)}>Procedi all’ordine <ArrowRight/></button></>}</div></aside>}
    {checkout && <aside className="overlay checkout-overlay"><form className="checkout" onSubmit={submitOrder}><button type="button" className="close" onClick={()=>setCheckout(false)}><X/></button><p className="eyebrow">CHECKOUT SICURO</p><h2>Quasi a casa.</h2><input required name="name" placeholder="Nome e cognome"/><input required type="email" name="email" placeholder="Email"/><input required name="address" placeholder="Indirizzo di consegna"/><div className="payment"><label><input type="radio" name="payment" value="Carta" defaultChecked/><CreditCard/> Carta di credito</label><label><input type="radio" name="payment" value="Bonifico bancario"/> Bonifico bancario</label></div><div className="bank-details"><b>Coordinate per il bonifico</b><span>Intestatario: DOC CARNI DI CICCARONE ANGELA &amp; C. – S.N.C.</span><span>IBAN: <strong>IT44U0815476070000260141622</strong></span><span>BIC: <strong>ICRAITRR4A0</strong></span><small>Indica il numero dell’ordine nella causale. L’ordine verrà elaborato alla ricezione del pagamento.</small></div><p className="order-total">Totale ordine <b>{money(total)}</b></p><button className="button dark full">Invia ordine <ArrowRight/></button><small>Il pagamento con carta richiede l’attivazione del gestore di pagamento.</small></form></aside>}
    {admin && <aside className="overlay admin-overlay"><div className="admin"><button className="close" onClick={()=>setAdmin(false)}><X/></button><p className="eyebrow">GESTIONE BOTTEGA</p><h2>Area amministratore</h2><div className="stats"><span><b>{products.length}</b>prodotti</span><span><b>{orders.length}</b>ordini</span><span><b>{money(orders.reduce((x,o)=>x+o.total,0))}</b>incassi</span></div><div className="admin-grid"><form onSubmit={createProduct}><h3>Aggiungi prodotto</h3><input required name="name" placeholder="Nome prodotto"/><input required type="number" step="0.01" name="price" placeholder="Prezzo €"/><input required name="weight" placeholder="Peso (es. 500 g)"/><input name="image" placeholder="URL foto (facoltativo)"/><textarea required name="description" placeholder="Breve descrizione"/><button className="button dark">Pubblica prodotto <Plus/></button></form><div className="orders"><h3>Ultimi ordini</h3>{orders.length?<table><thead><tr><th>Ordine</th><th>Cliente</th><th>Totale</th><th>Stato</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.id}<small>{o.date}</small></td><td>{o.customer}</td><td>{money(o.total)}</td><td><span className="status">{o.status}</span></td></tr>)}</tbody></table>:<div className="empty"><Package/><p>Gli ordini ricevuti compariranno qui.</p></div>}</div></div></div></aside>}
  </main>
}
