import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowRight, Camera, Check, ChevronRight, CreditCard, MapPin, Menu, Minus, Plus, ShoppingBag, Sparkles, Truck, X } from 'lucide-react'

type Product={id:number;name:string;price:number;weight:string;image:string;note:string}
const products:Product[]=[
 {id:1,name:'Soppressata di maiale',price:8.5,weight:'400 g',note:'Stagionata con lentezza',image:'https://images.unsplash.com/photo-1524438418049-ab2acb78927d?auto=format&fit=crop&w=900&q=85'},
 {id:2,name:'Capicollo selezione DOC',price:14.5,weight:'500 g',note:'Taglio italiano selezionato',image:'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=85'},
 {id:3,name:'Pancetta tesa al trancio',price:3.5,weight:'250 g',note:'Ricetta della tradizione',image:'https://images.unsplash.com/photo-1619012655280-484e4ba1c3c2?auto=format&fit=crop&w=900&q=85'},
 {id:4,name:'Box degustazione Vallo d’Oro',price:30,weight:'1,2 kg',note:'Il dono della tradizione',image:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=85'},
]
const euro=(x:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(x)

export default function LuxuryApp(){
 const [path,setPath]=useState(location.pathname),[open,setOpen]=useState(false),[mobile,setMobile]=useState(false),[cart,setCart]=useState<(Product&{q:number})[]>(()=>JSON.parse(localStorage.getItem('doc-lux-cart')||'[]')),[toast,setToast]=useState('')
 useEffect(()=>{const f=()=>setPath(location.pathname);addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[])
 useEffect(()=>localStorage.setItem('doc-lux-cart',JSON.stringify(cart)),[cart])
 useEffect(()=>{const move=(e:PointerEvent)=>{document.documentElement.style.setProperty('--mx',`${e.clientX}px`);document.documentElement.style.setProperty('--my',`${e.clientY}px`)};addEventListener('pointermove',move);return()=>removeEventListener('pointermove',move)},[])
 useEffect(()=>{const timer=setTimeout(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},40);return()=>clearTimeout(timer)},[path])
 const go=(to:string)=>{history.pushState({},'',to);setPath(to);setMobile(false);scrollTo({top:0,behavior:'smooth'})}
 const add=(p:Product)=>{setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,q:x.q+1}:x):[...c,{...p,q:1}]);setToast('Aggiunto al tuo scrigno DOC');setTimeout(()=>setToast(''),2200)}
 const total=useMemo(()=>cart.reduce((a,x)=>a+x.q*x.price,0),[cart])
 const update=(id:number,d:number)=>setCart(c=>c.flatMap(x=>x.id===id&&x.q+d===0?[]:x.id===id?{...x,q:x.q+d}:x))
 const order=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setCart([]);setOpen(false);setToast('Ordine ricevuto. Grazie per aver scelto DOC Carni.')}
 const nav=[['/','Maison DOC'],['/shop','Lo shop'],['/storia','La storia'],['/qualita','La qualità'],['/contatti','Contatti']]
 return <><div className="liquid-field" aria-hidden="true"><i/><i/><i/></div><div className="announcement">SPEDIZIONE OMAGGIO OLTRE 60€ <span>◆</span> CONSEGNA ESPRESSA IN 48 ORE</div><header className="lux-header glass"><button className="lux-logo" onClick={()=>go('/')}><b>DOC</b><span>CARNI</span><i>ATENA LUCANA · DAL 1961</i></button><nav>{nav.map(([u,n])=><button className={path===u?'active':''} onClick={()=>go(u)} key={u}>{n}</button>)}</nav><button className="bag" onClick={()=>setOpen(true)}><ShoppingBag/><em>{cart.reduce((a,x)=>a+x.q,0)}</em></button><button className="hamb" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>{mobile&&<div className="mobile-glass-menu glass">{nav.map(([u,n],i)=><button onClick={()=>go(u)} key={u}><span>0{i+1}</span>{n}<ArrowRight/></button>)}</div>}
 {toast&&<div className="lux-toast"><Check/> {toast}</div>}
 <div className="route-stage" key={path}>{path==='/'&&<Home go={go} add={add}/>} {path==='/shop'&&<Shop add={add}/>} {path==='/storia'&&<Story/>} {path==='/qualita'&&<Quality/>} {path==='/contatti'&&<Contact/>}</div>
 <footer><div className="footer-mark"><b>DOC</b><span>CARNI</span><p>Il sapore che sa di casa.<br/>Il lusso di una tradizione vera.</p></div><div><h4>La Maison</h4>{nav.slice(1).map(([u,n])=><button onClick={()=>go(u)} key={u}>{n}</button>)}</div><div><h4>Contatti</h4><p>Via Quercia, 6<br/>84030 Atena Lucana (SA)</p><p>+39 335 5280842<br/>doccarni1961@gmail.com</p></div><div><h4>Seguici</h4><a href="https://www.instagram.com/doccarniofficial/" target="_blank"><Camera/> Instagram</a><a href="https://www.facebook.com/doccarni" target="_blank">Facebook</a></div><small>© 2026 DOC CARNI · DOC CARNI DI CICCARONE ANGELA &amp; C. S.N.C.</small></footer>
 {open&&<aside className="cart-drawer"><button className="drawer-close" onClick={()=>setOpen(false)}><X/></button><p className="overline">IL TUO SCRIGNO</p><h2>La selezione<br/><i>è servita.</i></h2>{!cart.length?<div className="empty-cart"><ShoppingBag/><p>Nessun prodotto ancora.<br/>Scopri le nostre eccellenze.</p><button onClick={()=>{setOpen(false);go('/shop')}}>Vai allo shop <ArrowRight/></button></div>:<><div className="line-items">{cart.map(p=><div key={p.id}><img src={p.image}/><span><b>{p.name}</b><small>{euro(p.price)}</small><label><button onClick={()=>update(p.id,-1)}><Minus/></button>{p.q}<button onClick={()=>update(p.id,1)}><Plus/></button></label></span><strong>{euro(p.price*p.q)}</strong></div>)}</div><div className="drawer-total"><span>Totale</span><b>{euro(total)}</b><small>{total>=60?'Spedizione omaggio inclusa':'Spedizione calcolata al checkout'}</small></div><form onSubmit={order}><input required placeholder="La tua email" type="email"/><button className="gold-button">Completa l’ordine <ArrowRight/></button><p>Bonifico: IBAN <b>IT44U0815476070000260141622</b><br/>BIC: ICRAITRR4A0</p></form></>}</aside>}
 </>}
function Home({go,add}:{go:(x:string)=>void;add:(p:Product)=>void}){return <main><section className="lux-hero reveal"><div className="hero-text"><p className="overline">SALUMERIA ARTIGIANA DAL 1961</p><h1>L’arte del gusto.<br/><i>La firma del tempo.</i></h1><p className="lede">Dalla nostra bottega nel Vallo di Diano, una selezione di salumi italiani pensata per chi riconosce l’eccellenza.</p><button className="gold-button" onClick={()=>go('/shop')}>Entra nello shop <ArrowRight/></button><div className="hero-glass-stats glass"><span><b>100%</b> carni italiane</span><span><b>48h</b> a casa tua</span><span><b>0</b> conservanti</span></div></div><div className="hero-image"><div className="image-glass-tag glass">Lavorato nel<br/><b>Vallo di Diano</b></div><div className="heritage">40<small>ANNI DI<br/>TRADIZIONE</small></div></div></section><section className="gold-strip"><span>CARNE ITALIANA CERTIFICATA</span><span>✦</span><span>SENZA CONSERVANTI</span><span>✦</span><span>IL VALLO DI DIANO IN TAVOLA</span></section><section className="editorial reveal"><div className="editorial-img"></div><div className="editorial-glass glass"><p className="overline">L’ESSENZA DOC</p><h2>Il lusso è<br/><i>sapere aspettare.</i></h2><p>La qualità non ammette fretta. Ogni nostro salume segue il ritmo lento delle ricette di famiglia, con carni italiane scelte una ad una e gesti tramandati da quarant’anni.</p><button className="text-gold" onClick={()=>go('/storia')}>La nostra storia <ChevronRight/></button></div></section><section className="selection reveal"><div className="section-title"><p className="overline">LA SELEZIONE DELLA MAISON</p><h2>Da portare <i>in tavola.</i></h2><button onClick={()=>go('/shop')}>Vedi tutto <ArrowRight/></button></div><div className="product-grid">{products.slice(0,3).map(p=><ProductCard p={p} add={add} key={p.id}/>)}</div></section><section className="quote reveal"><Sparkles/><p>“Il vero sapore della tradizione valdianese,<br/><i>custodito in ogni fetta.</i>”</p></section></main>}
function Shop({add}:{add:(p:Product)=>void}){return <main className="page"><div className="page-hero reveal"><p className="overline">LO SHOP DOC CARNI</p><h1>Una dispensa<br/><i>di carattere.</i></h1><p>Salumi artigianali, box regalo e specialità del nostro territorio.</p></div><div className="shop-bar glass"><span>TUTTI I PRODOTTI</span><span>SPEDIZIONE GRATUITA OLTRE 60€</span></div><div className="product-grid wide reveal">{products.map(p=><ProductCard p={p} add={add} key={p.id}/>)}</div></main>}
function ProductCard({p,add}:{p:Product;add:(p:Product)=>void}){return <article className="product-card glass-card"><div className="product-photo" style={{backgroundImage:`url(${p.image})`}}><span className="glass">DOC SELECTION</span><button onClick={()=>add(p)}><Plus/></button></div><div className="product-meta"><small>{p.weight} · {p.note}</small><h3>{p.name}</h3><b>{euro(p.price)}</b></div></article>}
function Story(){return <main className="story-page"><section className="story-intro"><p className="overline">UNA STORIA LUNGA QUARANT’ANNI</p><h1>La memoria<br/><i>ha un sapore.</i></h1></section><section className="story-block"><div className="story-pic"></div><div><p>DOC Carni nasce quasi quarant’anni fa dalla passione e dalla determinazione di Gerardo e Angela: una scelta di vita che affonda le radici nella tradizione familiare della lavorazione delle carni.</p><p>Il cuore dell’azienda è la valorizzazione delle antiche ricette contadine. Non repliche del passato, ma gesti vivi, portati avanti con cura e rispetto.</p></div></section><section className="numbers"><div><b>40</b><span>anni di storia</span></div><div><b>100%</b><span>carni italiane</span></div><div><b>0</b><span>coloranti e conservanti</span></div></section></main>}
function Quality(){return <main className="quality-page"><section><p className="overline">IL NOSTRO IMPEGNO</p><h1>Solo ciò che<br/><i>merita la tavola.</i></h1><p>La qualità DOC Carni comincia prima della lavorazione: nella selezione rigorosa delle carni nazionali e nel rispetto di ogni materia prima.</p></section><div className="quality-list"><article><b>I</b><h3>Carni italiane certificate</h3><p>Tagli scelti e tracciabili, per un gusto che parte da una materia prima impeccabile.</p></article><article><b>II</b><h3>Ricette senza compromessi</h3><p>Niente coloranti, conservanti, glutine o lattosio. Solo ingredienti autentici.</p></article><article><b>III</b><h3>Il tempo come ingrediente</h3><p>Stagionature rispettose e lavorazioni pazienti per esprimere il carattere di ogni prodotto.</p></article></div></main>}
function Contact(){return <main className="contact-page"><section><p className="overline">VIENI A TROVARCI</p><h1>La nostra<br/><i>bottega.</i></h1><p>Nel cuore di Atena Lucana, dove la tradizione del Vallo di Diano incontra una nuova idea di gusto.</p></section><div className="contact-card"><MapPin/><h3>DOC Carni</h3><p>Via Quercia, 6<br/>84030 Atena Lucana (SA)</p><hr/><p>Tel. +39 335 5280842<br/>Tel. +39 0975 711 09<br/>doccarni1961@gmail.com</p><a href="https://www.google.com/maps/search/?api=1&query=Via+Quercia+6+Atena+Lucana" target="_blank">Apri su Maps <ArrowRight/></a></div></main>}
